### ISSUE TITLE
rspamd fails to resolve domains

### ISSUE THREAD

**Issue by phdoerfler** [r-raymond/nixos-mailserver#52]
On my server `rspamd` fills up the log with lines like these roughly once per minute:

```
Jan 03 18:10:00 nixos rspamd[800]: <cd3m9g>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.zen.spamhaus.org
Jan 03 18:10:02 nixos rspamd[800]: <cd3m9g>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.zen.spamhaus.org
Jan 03 18:10:04 nixos rspamd[800]: <zp979p>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.bl.ipv6.spameatingmonkey.net
Jan 03 18:10:05 nixos rspamd[800]: <o7e1zp>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve 1.0.0.127.list.dnswl.org
Jan 03 18:10:10 nixos rspamd[800]: <thbugu>; monitored; rspamd_monitored_dns_mon: cannot make request to resolve facebook.uribl.rambler.ru
```

I've only found https://github.com/vstakhov/rspamd/issues/1553 mentioning this and it suggests a config error.
Is anyone else getting these log messages?

**Comment by r-raymond** [comment]
This is indeed a problem with rspamd on nixos. It seems though as it does not jeopardize the functionality of it. rspamd website suggests hosting a DNS resolver, maybe that would solve the problem?

Btw, what rspamd version do you run? (I.e. are you on stable or unstable)

**Comment by erosennin** [comment]
Running a local DNS resolver fixed the problem for me:

```
services.kresd.enable = true;
networking.nameservers = [ "127.0.0.1" ];
```

**Comment by r-raymond** [comment]
Thanks for verifying this. I'll add this to the next version!

**Comment by phdoerfler** [comment]
@r-raymond I am on `17.09-small` so yes: stable.

**Comment by phdoerfler** [comment]
I was writing a PR for this, adding the solution by @erosennin but when I put both lines in my configuration, the name resolution broke:

`kresd` failed to start because of this:

    fetch of "https://data.iana.org/root-anchors/root-anchors.xml" failed: host or service not provided, or not known

I then removed this line:

    networking.nameservers = [ "127.0.0.1" ];

after which `kresd` was able to start. Then I added the line back into my config and this time it worked.

I am afraid NixOS applies the `networking.nameservers` before `kresd` has performed its initial setup therefore switing to a name resolution service which can't work. Then in turn the entire system is unable to perform any name resolution. How do we solve this?

**Comment by erosennin** [comment]
@phdoerfler this is fixed in master, [`kresd` now uses DNSSEC root trust anchors from nixpkgs](https://github.com/NixOS/nixpkgs/commit/3ab85ed1aca250501bcd098f5c304e3ddde96e79). The fix is already in the `nixos-unstable-small` channel (but not in `nixos-unstable` yet).

**Comment by phdoerfler** [comment]
@erosennin Interesting! My PR uses `insertNameservers` and I still get these errors logged :/
